### ISSUE TITLE
keyboard shortcut issue

### ISSUE THREAD

**Issue by caligabimba** [gaddafirusli/Preview-in-browser#3]
There seems to be an issue when hitting the shortcut while editing text in sketch. Sketch itself uses "cmd"+":" to open a dialog called "Show Spelling and Grammar" (see "Edit" > "Spelling"). Since you write the character ":" by hitting "shift"+"." this makes the shortcut "cmd"+"shift"+"." which is used in your script, too. I changed it to "cmd"+"shift"+"-" (manifest.json on line 7) and now it works just fine.

**Comment by gaddafirusli** [comment]
Hey @caligabimba, this doesn't sound like a real issue to me, as you aren't expected to hit preview while you're editing text. That being said, it seems like you manage to modify the shortcut keys to fit your workflow, so that's good.
