### ISSUE TITLE
No longer working with sketch 47

### ISSUE THREAD

**Issue by chanakairugal** [gaddafirusli/Preview-in-browser#4]
Its shows nothing on browser. 
<img width="1680" alt="screen shot 2017-11-18 at 9 42 51 am" src="https://user-images.githubusercontent.com/139042/32976791-e1d6a246-cc44-11e7-8fc0-a7679ff9b113.png">

**Comment by gaddafirusli** [comment]
@chanakairugal doesn't seems to be happening on my end. Can you verify this again?

**Comment by chanakairugal** [comment]
hmmm still not working mate :(

**Comment by gaddafirusli** [comment]
@chanakairugal Can u try to update to latest version 1.0.4 and let me know if this still happened?
