### ISSUE TITLE
can i open in other browser

### ISSUE THREAD

**Issue by ZTfer** [gaddafirusli/Preview-in-browser#7]
I do not want to preview in my default browser, and want to open in another browser such as firefox chrome, can you offer a setting in this sketch plugin? thanks very much

**Comment by gaddafirusli** [comment]
hey @ZTfer, sorry, I don't think that's a big use case and I'd prefer to keep this plugin as simple as possible for its intended use. You're welcomed to fork and add the functionality yourself :)
