### ISSUE TITLE
Safari browser starting to freeze

### ISSUE THREAD

**Issue by AndrejusZem** [gaddafirusli/Preview-in-browser#8]
Hello, 

I noticed that after using plugin more times in a day Safari browser starting to freeze and the only solution what I found is to restart the laptop. 
Is anyone having the same issue? Is this problem related only with the Safari or Chrome does the same?

Thanks.

**Comment by gaddafirusli** [comment]
Hey @AndrejusZem, I've been using it heavily (on Chrome only) for the past few days, and doesn't seem to cause any issue. They're possibilities that your design is heavy and the generated image have a huge size, causing it to use a lot of memory space. I won't be able to do anything about it. Sorry.
